version: "3.8"
services:
  satellite:
    build: .
    image: gunimoon/wyoming-satellite
    restart: unless-stopped    
    volumes:
      - ./sounds:/sounds
      - ~/.config/pulse:/root/.config/pulse
    ports:
      - "10700:10700"
    network_mode: host
    command:    
      - "--debug"
      - "--name"
      - "kitchen_satellite"
      - "--uri"
      - "tcp://0.0.0.0:10700"
      # - "--mic-uri"
      # - "tcp://microphone:10600"
      # - "--snd-uri"
      # - "tcp://192.168.1.172:10601"
      - "--mic-command"
      - "arecord --device \"pulse\" -r 16000 -c 1 -f S16_LE -t raw"
      - "--snd-command"
      - "aplay --device \"pulse\" -r 22050 -c 1 -f S16_LE -t raw"
      - "--awake-wav"
      - "/sounds/awake.wav"
      - "--done-wav"
      - "/sounds/done.wav"
      - "--timer-started-command"
      - "/sounds/timer_started.sh"
      # - "--event-uri"
      # - "tcp://127.0.0.1:10500"
      # - "--wake-uri"
      # - "tcp://openwakeword:10400"
      # - "--wake-word-name"
      # - "wall-e"
      - "--timer-finished-wav"     
      - "/sounds/timer_finished.wav"
      - "--timer-finished-wav-repeat"
      - "5"
      - "2"
      - "--mic-noise-suppression"
      - "1"
      - "--vad"
    environment:
    # - "PULSE_SERVER=host.docker.internal
      - "PULSE_SERVER=127.0.0.1"
