version: "3.8"
services:
  satellite:
    build: .
    image: gunimoon/wyoming-satellite
    restart: unless-stopped    
    volumes:
      - ./wyoming-satellite/sounds:/sounds
      - ~/.config/pulse:/root/.config/pulse
    ports:
      - "10700:10700"
    command:    
      - "--debug"
      - "--name"
      - "living_room"
      - "--uri"
      - "tcp://0.0.0.0:10700"
      # - "--mic-uri"
      # - "tcp://microphone:10600"
      # - "--snd-uri"
      # - "tcp://192.168.1.172:10601"
      - "--mic-command"
      - "arecord --device \"pulse\" -r 16000 -c 1 -f S16_LE -t raw"
      - "--snd-command"
      - "aplay --device \"pulse\" -r 22050 -c 1 -f S16_LE -t raw"
      - "--awake-wav"
      - "/sounds/awake.wav"
      - "--done-wav"
      - "/sounds/done.wav"
      # - "--event-uri"
      # - "tcp://127.0.0.1:10500"
      # - "--wake-uri"
      # - "tcp://openwakeword:10400"
      # - "--wake-word-name"
      # - "wall-e"
    environment:
      - "PULSE_SERVER=host.docker.internal"
